tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"

brew "n"
brew "azure-cli"
brew "terraform"
brew "mas"
brew "python"
brew "kubectx"
brew "gradle"
brew "fzf"
brew "k9s"
brew "jq"
brew "go"
brew "sops"
brew "helm"
brew "buildpacks/tap/pack"
brew "kube-ps1"
brew "jenv"
brew "nmap"
brew "mysql-client"
brew "mysql-client@5.7" 
brew "telepresence"
brew "fluxcd/tap/flux"
brew "bats-core"
brew "lacework/tap/lacework-cli"
brew "helmfile"
brew "velero"

cask "docker"
cask "firefox"
cask "google-cloud-sdk"
cask "visual-studio-code"
cask "alfred"
cask "sourcetree"
cask "spotify"
cask "Postman"
cask "intellij-idea"
cask "clipy"
cask "kitty"
cask "slack"
cask "robo-3t"
cask "google-drive"
cask "1password"
cask "caffeine"
cask "karabiner-elements"
cask "clockify"
cask "lens"

mas "Pixelmator Pro", id: 1289583905
mas "BetterSnapTool", id: 417375580
